In [1]:
import numpy as np
import h5py
import os

# Localization of h5 for all data
directory = 'data/DarkSUSY.h5'
# Open file *.h5 of data
hf = h5py.File(directory, 'r')

Vect_MNeuL = [10]
Vect_MNeuD = [0.25, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]  # mass of dark neutrino
Vect_MPhoD = [0.25, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]  # mass of  dark photon
Vect_TcPhoD = [0, 5, 10, 20, 30, 40, 50, 60, 70, 80, 90, 100]  # values of life time (Tc)
Vect_Card = ["HL", "CMS"]

out_CMS = np.zeros([len(Vect_MNeuL), len(Vect_MNeuD),
                    len(Vect_MPhoD), len(Vect_TcPhoD)], dtype=int)
out_HL  = np.zeros([len(Vect_MNeuL), len(Vect_MNeuD),
                    len(Vect_MPhoD), len(Vect_TcPhoD)], dtype=int)

#print out_CMS

i_MNeuL = [-1]
for MNeuL in Vect_MNeuL:
    i_MNeuL += 1
    i_MNeuD = [-1]
    for MNeuD in Vect_MNeuD:
        i_MPhoD = [0]
        for MPhoD in Vect_MPhoD:
            if MNeuD + MPhoD <= MNeuL:  # condition mass equilibrium
                i_TcPhoD = [0]
                for TcPhoD in Vect_TcPhoD:
                    for Card in ["HL", "CMS"]:
                        direction = "MNeuL_" + str(MNeuL) + "/MNeuD_" + str(MNeuD) + \
                                    "/MPhoD_" + str(MPhoD) + "/LifeTime/TcPhoD_" + str(TcPhoD) + \
                                    "/Card_" + Card
                        # print direction
                        group = hf.get(direction)
                        print np.array(group.get('Entries')), type(int(np.array(group.get('Entries'))))
                        if Card is "HL":
                            out_HL[i_MNeuL, i_MNeuD, i_MPhoD, i_TcPhoD] = int(np.array(group.get('Entries')))
                        elif Card is "CMS":
                            out_CMS[i_MNeuL, i_MNeuD, i_MPhoD, i_TcPhoD] = int(np.array(group.get('Entries')))

hf.close()

print out_HL
print out_CMS


TypeError: 'int' object is not iterable

In [ ]:
from modules.darkSUSY.classDarkSUSY import *
from modules.general.F_search import *
from modules.graph.histograms import *

from IPython.display import clear_output
import matplotlib.pyplot as plt
from matplotlib import cm
import numpy as np
import h5py
import os

In [ ]:
name = "data/ALL//LOG_Mu4_DarkSUSY_HL_Event_10000_MNeuL_10_MNeuD_0.25_MPhoD_2_TcPhoD_5_.txt"
FileROOT = open(name, 'r')
Reduction_Event = []
for line in FileROOT:
    try:
        float(line)
        Reduction_Event.append(float(line))
        #print str(line)
    except ValueError:
        continue
        
FileROOT.close()
print Reduction_Event
# DarkFileTemp.Obtein(var, order=False)
#DarkFileTemp.Mu_DiMu[:,0]

In [ ]:
directory = 'data/DarkSUSY.h5'
hf = h5py.File(directory, 'w')
#direction = "MNeuL_" + str(MNeuL) + "/MNeuD_" + str(MNeuD) + "/MPhoD_" + str(MPhoD)
#hf.create_group(direction)
gg=hf.require_group("directionn")
hf.close()
print gg

In [ ]:
from modules.darkSUSY.classDarkSUSY import *
from modules.general.F_search import *
from modules.graph.histograms import *

import matplotlib.pyplot as plt
from matplotlib import cm
import numpy as np

Delphes_DIR = "/home/franky8939/PROGRAMAS/MG5_aMC_v2_6_7/Delphes/"  # Directory local of Delphes
ROOT_DIR = "/home/franky8939/PROGRAMAS/root-6.18.02/"  # Directory local of Root
fbash(Delphes_DIR, ROOT_DIR)  # path in bash of Delphes and Root

# CLASE DARKSUSY
DarkFile = DarkSUSY()  # inicializar la clase

In [3]:
# BUSCAR DATA
Event = 10000
Vect_MNeuL = [10]
Vect_MNeuD = [0.25]
Vect_MPhoD = [0.25]  # [0.25, 1, 2, 3, 4, 5]  # masa de los photons
Vect_TcPhoD = [0, 5, 10, 20, 30, 40, 50, 60, 70, 80, 90, 100]  # valores de Tc
Vect_Card = ["HL", "CMS"]
# BUSCANDO ARCHIVO DEFAULT
directory = "data/ALL/"
particle = "Muon"
var = "Eta"
for MNeuL in Vect_MNeuL:
    for MNeuD in Vect_MNeuD:
        for MPhoD in Vect_MPhoD:
            for TcPhoD in Vect_TcPhoD:
                #for Card in Vect_Card:
                fileROOT = FindROOT(Event=Event,
                                    Card=None, 
                                    MNeuL=MNeuL, 
                                    MNeuD=MNeuD, 
                                    MPhoD=MPhoD, 
                                    TcPhoD=TcPhoD, 
                                    include=["Mu4_DarkSUSY", "_.root", "HL"], 
                                    directory="data/ALL/")


plt.grid(True)
plt.xlabel('Value of Eta')
plt.ylabel('Normalize Probability')
plt.xlim(-4,4)
plt.legend(["Card = HL","Card = CMS"])
plt.savefig("Change of eta.pdf")
plt.savefig("Change of eta.png")
plt.show()
                    #fileROOT = FindROOT(Event, Card, MNeuL, MNeuD, MPhoD, TcPhoD, directory)

 :: File localizado correctamente :: 
 :: archivo :: Mu4_DarkSUSY_HL_Event_10000_MNeuL_10_MNeuD_0.25_MPhoD_0.25_TcPhoD_0_.root
 :: File localizado correctamente :: 
 :: archivo :: Mu4_DarkSUSY_HL_Event_10000_MNeuL_10_MNeuD_0.25_MPhoD_0.25_TcPhoD_5_.root
 :: File localizado correctamente :: 
 :: archivo :: Mu4_DarkSUSY_HL_Event_10000_MNeuL_10_MNeuD_0.25_MPhoD_0.25_TcPhoD_10_.root
 :: File localizado correctamente :: 
 :: archivo :: Mu4_DarkSUSY_HL_Event_10000_MNeuL_10_MNeuD_0.25_MPhoD_0.25_TcPhoD_20_.root
 :: File localizado correctamente :: 
 :: archivo :: Mu4_DarkSUSY_HL_Event_10000_MNeuL_10_MNeuD_0.25_MPhoD_0.25_TcPhoD_30_.root
 :: File localizado correctamente :: 
 :: archivo :: Mu4_DarkSUSY_HL_Event_10000_MNeuL_10_MNeuD_0.25_MPhoD_0.25_TcPhoD_40_.root
 :: File localizado correctamente :: 
 :: archivo :: Mu4_DarkSUSY_HL_Event_10000_MNeuL_10_MNeuD_0.25_MPhoD_0.25_TcPhoD_50_.root
 :: File localizado correctamente :: 
 :: archivo :: Mu4_DarkSUSY_HL_Event_10000_MNeuL_10_MNeuD_0.25_MPhoD

In [ ]:
for fill in fileROOT:
    if fileROOT is not None:
        DarkFileN = DarkFile  # new
        DarkFileN.Add_File("data/ALL/" + fileROOT)
        DarkFileN.Select_two_dimuon()
        Var = DarkFileN.Obtein(var, particle="Muon", order=False)
        
        print(Var.flatten())
        plt.hist(Var.flatten(),  bins=40, alpha=0.7, normed=1)



In [11]:
"_.root" not in "Mu4_DarkSUSY_HL_Event_10000_MNeuL_10_MNeuD_0.25_MPhoD_0.25_TcPhoD_0_.txt"

True

In [ ]:
# BUSCAR DATA
Event = 10000
Vect_MNeuL = [10]
Vect_MNeuD = [0.25]
Vect_MPhoD = [0.25]  # [0.25, 1, 2, 3, 4, 5]  # masa de los photons
Vect_TcPhoD = [5, 10, 50]  # [0, 5, 10, 20, 30, 40, 50, 60, 70, 80, 90, 100]  # valores de Tc
Vect_Card = ["HL"]
# BUSCANDO ARCHIVO DEFAULT
directory = "data/ALL/"
particle = "Muon"
var = "D0"
for MNeuL in Vect_MNeuL:
    for MNeuD in Vect_MNeuD:
        for MPhoD in Vect_MPhoD:
            for TcPhoD in Vect_TcPhoD:
                for Card in Vect_Card:
                    fileROOT = FindROOT(Event, Card, MNeuL, MNeuD, MPhoD, TcPhoD, directory)
                    if fileROOT is not None:
                        # print(fileROOT)
                        # clear_output()
                        #DarkFileNew = DarkFile  # new
                        #DarkFileNew.Add_File(directory + "/" + fileROOT)
                        #DarkFileNew.Select_two_dimuon()
                        #data = DarkFileNew.Obtein("Eta", particle="particle", order=False)
                        
                        DarkFileN = DarkFile  # new
                        DarkFileN.Add_File("data/ALL/" + fileROOT)
                        DarkFileN.Select_two_dimuon()
                        Var = DarkFileN.Obtein(var, particle=particle, order=False)
                        #print Var.flatten()
                        plt.hist(Var.flatten(),  bins=120, alpha=0.5, normed=1)

plt.grid(True)
plt.xlabel('Value of D0')
plt.ylabel('Normalize Probability')
plt.xlim(-50,50)
plt.ylim([0,0.1])
plt.legend(["ct = 5 mm","ct = 10 mm","ct = 50 mm"])
plt.savefig("Change of D0.pdf")
plt.savefig("Change of D0.png")
plt.show()

In [ ]:

# Para entries
# BUSCAR DATA
Event = 10000
Vect_MNeuL = [10]
Vect_MNeuD = [0.25]
Vect_MPhoD = [0.25, 1, 2, 3, 4, 5]  # masa de los photons
Vect_TcPhoD = [0, 5, 10, 20, 30, 40, 50, 60, 70, 80, 90, 100]  # valores de Tc
Vect_Card = ["CMS", "HL"]
# BUSCANDO ARCHIVO DEFAULT
directory = "data/ALL/"
particle = "Muon"
var = "Entries"
EntriesCMS=np.zeros((len(Vect_MPhoD), len(Vect_TcPhoD)))
EntriesHL=np.zeros((len(Vect_MPhoD), len(Vect_TcPhoD)))
print EntriesHL

i = 0
j = 0
for MNeuL in Vect_MNeuL:
    for MNeuD in Vect_MNeuD:
        for MPhoD in Vect_MPhoD:
            if MPhoD is not Vect_MPhoD[0]:
                i += 1
                j = 0
            for TcPhoD in Vect_TcPhoD:
                if TcPhoD is not Vect_TcPhoD[0]:
                    j +=1
                for Card in Vect_Card:
                    fileROOT = FindROOT(Event, Card, MNeuL, MNeuD, MPhoD, TcPhoD, directory)
                    if fileROOT is not None:mass1 = (self.File.Muon.At(di_muon
                        #print i, j                        
                        DarkFileN = DarkFile  # new
                        DarkFileN.Add_File("data/ALL/" + fileROOT)
                        if Card == "HL":
                            EntriesHL[i,j] = DarkFile.Entries
                        if Card == "CMS":
                            EntriesCMS[i,j] = DarkFile.Entries
                        
                        
                        #DarkFileN.Select_two_dimuon()
                        #Var = DarkFileN.Obtein("Eta", particle="Muon", order=False)
                        
                        #print(Var.flatten())
                        #plt.hist(Var.flatten(),  bins=40, alpha=0.7, normed=1)

#plt.grid(True)
#plt.show()
#plt.savefig("Variable temporal.pdf")





In [22]:
print EntriesCMS
print EntriesHL



 

[[881. 500. 227.  72.  41.  25.  16.  15.   8.   5.   9.   2.]
 [492. 485. 417. 243. 167. 111.  72.  77.  35.  42.  46.  28.]
 [497. 488. 465. 420. 298. 232. 182. 179. 130. 127.  90.  75.]
 [470. 476. 480. 438. 376. 318. 284. 232. 199. 178. 163. 143.]
 [494. 525. 512. 459. 436. 407. 371. 311. 272. 244. 213. 183.]
 [501. 496. 494. 484. 450. 450. 397. 393. 311. 301. 281. 254.]]
[[1625.  902.  433.  179.   77.   47.   39.   44.   17.   16.   11.    6.]
 [1172. 1053.  902.  592.  411.  348.  212.  162.  139.  106.   91.   76.]
 [1135. 1102. 1028.  898.  706.  587.  507.  388.  326.  300.  238.  215.]
 [1117. 1111. 1098.  963.  876.  774.  652.  548.  493.  373.  380.  338.]
 [1158. 1154. 1149. 1063.  934.  885.  782.  705.  625.  584.  512.  502.]
 [1204. 1267. 1223. 1220. 1134.  973.  956.  818.  809.  758.  688.  590.]]
